### ISSUE TITLE
Allow user input of sound sequences

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#10]
**Tasks:**
- [x] Create input fields for:
  - [x] clef
  - [x] octave
  - [x] note values (C, D, E, F, G, A, H, C)
  - [x] flat, sharp, natural
- [x] Create buttons to delete input
- [x] Evaluate input
- [x] Pass input to search controller
