### ISSUE TITLE
Search sound sequences in corpus

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#14]
**Predecessors:**
- [x] #10 

---

**Tasks:**
- [x] generate query from user input
- [x] fire query to data
- [x] preprocess results
- [x] store results in db
- [x] pass results according controller
- [x] testing

**Comment by led13714** [comment]
extensive testing: #42
