### ISSUE TITLE
Visualise search results in a list

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#17]
**Predecessors:**
- [ ] #14 

---

**Tasks:**
- [x] create result view
- [x] display searched pattern
- [x] allow editing pattern (step back to search)
- [x] list results with:
  - [x] title
  - [x] interpret
  - [x] number of occurences inside file
