### ISSUE TITLE
Create result extracts

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#18]
**Predecessors:**
- [x] #17 

---

**Tasks:**
- [x] generate extracts for result:
  - [x] embedd result in few staves
- [x] highlight result

**Comment by freakimkaefig** [comment]
- [x] add ties between notes

**Comment by freakimkaefig** [comment]
remove ties from extract rendering (problems with ties from one to following line)

**Comment by freakimkaefig** [comment]
- [x] Revise pattern highlighting

Highlight only notes from pattern, instead of all notes inside the measure.
