### ISSUE TITLE
Upload functionality

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#2]
**Predecessors:**
- [x] #4 

---

**Tasks:**
- [x] Integrating dropzone.js (http://chrisbeaver.com/2014/09/using-dropzonejs-laravel-4/)
- [x] Configure frontend
  - [x] Laravel view
  - [x] frontend logic with dropzone.js
- [x] configure backend
  - [x] laravel route
  - [x] database caching of uploaded files

**Comment by led13714** [comment]
während dem hochladen, einzelne schritte (auch analyseschritte) mit angeben

**Comment by freakimkaefig** [comment]
- [ ] move upload handling from routes to UploadController
- [ ] correct handling when queue is completed
- [ ] error handling
