### ISSUE TITLE
Playback of extract in search result detail & of pattern in pattern creation

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#21]
**Predecessors:**
- [x] #18 

---

**Tasks:**
- [x] create controls
  - [x] play
  - [x] pause (can't be implemented atm)
  - [x] stop
- [x] play extract with midi.js
- [x] play pattern on pattern creation -> ../pattern

**Comment by led13714** [comment]
Playback of created patterns on ../pattern?

**Comment by freakimkaefig** [comment]
Manu hat glaub ich gemeint, dass es schon Sinn macht, damit ma sich mal anhören kann, nach was ma überhaupt sucht.

**Comment by led13714** [comment]
# WAIT UNTIL PATTERN IS CORRECTLY CREATED

## currently missing 'type' property within notes

**Comment by led13714** [comment]
pause control can't be implemented atm, due to lack of midi creation within implementation of MIDI.js.
could be fixxed if MIDI is generated using base64 lib. 
(MIDI.js is using a different player [within player.js lib inside of MIDI.js] which has sufficient functionality for pausing playback, if MIDI is generated with base64 & not passed as integers to MIDI Object.)

**Comment by led13714** [comment]
playback implemented for all pattern-modes.
playing C4 on rhythm mode.
playing 1/4 notes on soundsequence mode.
