### ISSUE TITLE
User input with mouse

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#23]
**Predecessors:**
- [x] #10 

---

**Tasks:**
- [x] input field is visualized as a stave
- [x] enabling user input by clicking on stave
- [x] input controls used from #10 #11 #12
