### ISSUE TITLE
Garbage Collector for outdated db entries

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#25]
**Tasks:**
- [x] recognition of outdated data
- [x] flush user data from table
  - [x] users
  - [x] uploads
  - [x] results
- [x] remove associated files for uploads from server

**Comment by freakimkaefig** [comment]
Remove files from server!
