### ISSUE TITLE
Export analysis data

### ISSUE THREAD

**Issue by led13714** [freakimkaefig/Music-XML-Analyzer#29]
**Tasks:**
- [x] generate csv/xls
- [x] allow user download
- [x] fill csv/xls with data
- [x] if xls: create multiple worksheets
