### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#4]
**Tasks:**
- [x] draw ERM (with Dia)
- [x] create tables from ERM
- [x] configure laravel migrations
- [x] explain "php artisan migrate:refresh" to team members
