### ISSUE TITLE
Queries for automatic analysis after upload

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#6]
**Tasks:**
- [x] Write queries for (php XPath):
  - [x] counting notes
  - [x] determine clef
  - [x] counting intervals
  - [x] counting&determine note types
  - [x] determine instruments
  - [x] determine interpret & title
  - [x] determine key (aka "tonart", z.B. C-Dur)
  - [x] determine octaves / tritonus
  - [x] determine meter (aka "taktart", z.B. 4/4)
  - [x] count strokes (aka "measure")
  - [x] count breaks (aka "rest")
  - [x] count note values
  - [x] determine most frequent note
  - [x] wrap all return values & save in db
