### ISSUE TITLE
Analyse uploaded data

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#8]
**Predecessors:**
- [x] #6  

---

**Tasks:**
- [x] Research about XPath in PHP
- [x] Define model of created Patterns
- [x] Research about XQuery in PHP
- [x] Handle automatic analysis after files uploaded
- [x] translate incoming pattern to XQuery
- [x] Cache results in database

**Comment by led13714** [comment]
xquery wahrscheinlich sinnvoller für komplexere querys
